export enum ORDER_STATUS {
    AWAITING_PAYMENT = 'AWAITING_PAYMENT',
    PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
    PAYMENT_FAILED = 'PAYMENT_FAILED',
    PROCESSING = 'PROCESSING',
    COURIER_REQUESTED = 'COURIER_REQUESTED',
    SHIPPED = 'SHIPPED'
}
